In [33]:
import pandas as pd

df = pd.read_csv('../pandas/products.csv')
print(df)

     Index                                    Name  \
0        1                 Thermostat Drone Heater
1        2   Ultra Speaker Iron Grill Advanced One
2        3                 Watch Headphones Kettle
3        4   Portable Toaster Clock Monitor Silent
4        5                        Pro Toaster Oven
..     ...                                     ...
995    996  Silent Router Phone Portable Automatic
996    997              Digital Treadmill Clean Go
997    998                  Wireless Vacuum Shaver
998    999  Portable Cooker Brush 360 Digital Mini
999   1000          Smart Watch Edge Digital Sense

                                         Description  \
0             Consumer approach woman us those star.
1    Point suggest easy money operation could white.
2                           Reach husband education.
3              Always choose school poor table main.
4            Worry put discuss easy back too career.
..                                               ...
995            Piece the fight near never once bank.
996                 Apply drive outside reach apply.
997              Line cup course student each about.
998      History feel worry painting only power bad.
999                           Pay image either rest.

                            Brand                Category  Price Currency  \
0                     Bradford-Yu      Kitchen Appliances     74      USD
1                   Douglas Group       Fitness Equipment    510      USD
2                   Landry-Austin  Beauty & Personal Care    254      USD
3         Odom, Norton and Foster                  Makeup     69      USD
4    Fowler, Mendoza and Mcdaniel              Automotive    525      USD
..                            ...                     ...    ...      ...
995                 Huffman Group            Toys & Games    903      USD
996                Woodward Group            Toys & Games      8      USD
997                Ramos-Cardenas  Beauty & Personal Care    615      USD
998                 Hooper-Bender          Men's Clothing    811      USD
999                    Campos Inc      Kitchen Appliances    867      USD

     Stock            EAN             Color         Size   Availability  \
0      139  8619793560985            Orchid       Medium      backorder
1      351  3057216124300    MediumSeaGreen        Small      backorder
2      409  9825254410556          Lavender          XXL      pre_order
3      119  9490814777808              Pink           XL       in_stock
4      727  4726650403799        LightCoral           XL       in_stock
..     ...            ...               ...          ...            ...
995    737  8227581307423  MediumAquaMarine           XL  limited_stock
996    330   522633507294     PaleVioletRed       Medium   out_of_stock
997    630  1892829625606     PaleVioletRed  Extra Large      pre_order
998    566  1683591150065        LightGreen            S       in_stock
999    769  8697154897673         Gainsboro     50x70 cm  limited_stock

     Internal ID
0             38
1             27
2              2
3             94
4             95
..           ...
995           33
996            9
997            4
998           65
999           10

[1000 rows x 13 columns]

In [34]:
df.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         1000 non-null   int64
 1   Name          1000 non-null   object
 2   Description   1000 non-null   object
 3   Brand         1000 non-null   object
 4   Category      1000 non-null   object
 5   Price         1000 non-null   int64
 6   Currency      1000 non-null   object
 7   Stock         1000 non-null   int64
 8   EAN           1000 non-null   int64
 9   Color         1000 non-null   object
 10  Size          1000 non-null   object
 11  Availability  1000 non-null   object
 12  Internal ID   1000 non-null   int64
dtypes: int64(5), object(8)
memory usage: 101.7+ KB

In [36]:
df.describe()

             Index        Price        Stock           EAN  Internal ID
count  1000.000000  1000.000000  1000.000000  1.000000e+03  1000.000000
mean    500.500000   506.549000   501.782000  5.130255e+12    47.690000
std     288.819436   283.773556   292.151318  2.907413e+12    28.984202
min       1.000000     1.000000     2.000000  4.842647e+08     1.000000
25%     250.750000   284.750000   243.000000  2.699217e+12    22.000000
50%     500.500000   497.500000   504.000000  5.118167e+12    46.000000
75%     750.250000   757.250000   750.250000  7.653439e+12    74.000000
max    1000.000000   999.000000   999.000000  9.994627e+12    99.000000

In [37]:
df.columns

Index(['Index', 'Name', 'Description', 'Brand', 'Category', 'Price',
       'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability',
       'Internal ID'],
      dtype='object')

In [38]:
df["Brand"]

0                       Bradford-Yu
1                     Douglas Group
2                     Landry-Austin
3           Odom, Norton and Foster
4      Fowler, Mendoza and Mcdaniel
                   ...
995                   Huffman Group
996                  Woodward Group
997                  Ramos-Cardenas
998                   Hooper-Bender
999                      Campos Inc
Name: Brand, Length: 1000, dtype: object

In [ ]:
len(df["Brand"])

1000

In [40]:
df.index

RangeIndex(start=0, stop=1000, step=1)